### PR TITLE
systemd setup, redid install.sh script.

### PR DESCRIPTION
**Pull request by wwiv**
big change to install scripts.

### CODE REVIEW

**Comment by wwiv** [comment]
@granitepenguin WDYT?

**Comment by granitepenguin** [comment]
Hmm, the problem with this is /etc/default is a Debian-specific thing. The reason I did what I did is it's based on the install location of the bbs itself. If someone is using a different distro (e.g., fedora), that won't be there

**Comment by wwiv** [comment]
Looks like fedora has both /etc/default and /etc/sysconfig

See https://fedorahosted.org/fpc/ticket/152 and https://docs.fedoraproject.org/en-US/Fedora/18/html/Installation_Guide/sn-medialess-editing-grub-conf.html

**Comment by granitepenguin** [comment]
/etc/default is an abberation forced by a small subset (most notably grub).  

The point is it's not the best option to assume it exists.  A better option would be a /etc/wwiv directory to put whatever we need.  This gets back to the whole point of what I was going for in the first place: keeping everything in the WWIV_DIR as much as possible instead of spreading things all over the place.

**Comment by granitepenguin** [comment]
using the "say" command is not recommended.  It's not standard.  Why use that instead of echo?

**Comment by granitepenguin** [comment]
Never mind.. I see it's a function you created for inside the script, not an external program.

**Pull request merged**
