### PR TITLE
Added 'Last Net Connections' to display after Last Callers

### PR DESCRIPTION
**Pull request by MorgulWWIV**
Created a Last Net Conection display, showing the last 6 network connections - time, date, bytes sent, bytes received, node and network, and the name of the connection.  Similar in style to the Last Users list, and displaying right after it.

### CODE REVIEW

**Comment by wwiv** [comment]
Thanks, I was thinking that this may be cool to do as an external program, and call it from the logon command.  What do you think about that?

**Comment by robertstinnett** [comment]
What about making this a command available off the menu?  This would be cool to have available as a privileged command off the menu.

**Comment by MorgulWWIV** [comment]
> 
> 
> Thanks, I was thinking that this may be cool to do as an external program, and call it from the logon command. What do you think about that?

The codes doesn't take up too much room, I don't think, and should be ok in the main code.  Leaving it there would be one less program to write/have in the bbs directory.  We could possibly add a toggle in the configuration files so it can be turned off if a sysop doesn't want it or the board isn't networked.

**Comment by MorgulWWIV** [comment]
> 
> 
> What about making this a command available off the menu? This would be cool to have available as a privileged command off the menu.

That should be fairly easy, as it's a simple call to make.  Hardest part is finding an available keypress to use. :)

**Comment by robertstinnett** [comment]
> > What about making this a command available off the menu? This would be cool to have available as a privileged command off the menu.
> 
> That should be fairly easy, as it's a simple call to make. Hardest part is finding an available keypress to use. :)

//LASTNET ?

**Pull request merged**
