### PR TITLE
wfndfile_unix now uses stat instead of relying on non posix dirent st…

### PR DESCRIPTION
**Pull request by ghost**
…ructures

On my system the menu editor was not listing any entries in the menu list. Fixed it by switching to stat instead of relying on the non standard d_type

### CODE REVIEW

**Comment by wwiv** [comment]
wow. what system is that?  

yup, POSIX only requires 2 fields there:  d_ino and d_name
http://pubs.opengroup.org/onlinepubs/009695399/basedefs/dirent.h.html

**Comment by ghost** [comment]
Scientific Linux 7.3 (Red Hat clone)

**Comment by ghost** [comment]
I just had a closer look, seems like it needs _BSD_SOURCE defined to include that stuff.

**Comment by wwiv** [comment]
ahh ok. Or check for _DIRENT_HAVE_D_TYPE before using it, and then fallback to stat... ick.

thanks for the patch, I didn't realize some linux'es didn't have it, since it was on debian and even osx (of course, it's a BSD'ism).

**Pull request merged**
