### PR TITLE
Start of SSH support

### PR DESCRIPTION
**Pull request by wwiv**
TL;DR Don't use it yet.

It doesn't really work but for testing things out.

Use -XS instead of -XT on the commandline for SSH (instead of telnet)
expect lots of debug info.
expect to have to press enter on the bbs console since I'm still debugging and that's how you wait for the debugger
expect it to not exit by itself...

### CODE REVIEW

**Comment by granitepenguin** [comment]
Make sure it's possible to set non-standard ports. Especially once things are working for Linux, it will be important for access to the regular ssh connection to the OS.

**Comment by TRI0N** [comment]
Already got that covered..  Well for the Windows TelnetServer at least..

**Comment by TRI0N** [comment]
I have successfully connect to WWIV via SSH thru TelnetServer. I am now updating TelnetServer to listen on a 2 port configuration.

**Comment by TRI0N** [comment]
#685 SSH Is Now Supported!

**Pull request merged**
